<a href="https://colab.research.google.com/github/supergoa/Cap4630Repository/blob/master/HW_4/HW4Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
def maxpooling2d(im, s):
  if im.shape[0] != im.shape[1]:
    raise ValueError("Input Matrix not square")
  if im.shape[0] % s != 0:
    raise ValueError("Input Matrix not evenly divisible by s")
  n = len(im[0])
  k = int(n/s)
  om = np.zeros(k*k, dtype=int).reshape(k,k)
  for i in range(0, n, s):
    for j in range(0, n, s):
      maximum = 0
      for k in range(0, s):
        for l in range(0, s):
          maximum = max(maximum, im[i+k][j+l])
      om[i//s][j//s] = maximum
  print(om)
  return om

import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
 # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4 2]
 [2 4]]
[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
