<a href="https://colab.research.google.com/github/supergoa/Cap4630Repository/blob/master/HW_4/HW4Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
def conv2d(im, km):
  im = np.array(im)
  km = np.array(km)
  s = len(km[0])
  n = len(im[0])
  if im.shape[0] < km.shape[0]:
    return []
  else:
    om = np.zeros((n-s+1)*(n-s+1), dtype=int).reshape((n-s+1),(n-s+1))
  for i in range(0, n-s+1):
    for j in range(0, n-s+1):
      conv = 0
      for k in range(0, s):
        for l in range(0, s):
          conv += im[i+k][j+l] * km[k][l]
      om[i][j] = conv
  return om

from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  #print(input_mat[i])
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  #if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #  output_mat = []
  #else:
  #  output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

[]
Correct output!

